name: CD Pipeline

on:
  workflow_run:
    workflows: [ "CI Pipeline" ]
    types: [ "completed" ]

jobs:

  deploy:

    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up environment file
      run: |
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" > server/.env
        echo "NODE_ENV=production" >> server/.env
        echo "PORT=8000" >> server/.env
        echo "CORS_ORIGIN=${{ secrets.CORS_ORIGIN || '*' }}" >> server/.env
        echo "LOG_LEVEL=${{ secrets.LOG_LEVEL || 'info' }}" >> server/.env

    - name: Stop existing containers
      run: |
        cd server
        sudo docker compose -f docker-compose.prod.yml down || true

    - name: Build and start application
      run: |
        cd server
        sudo docker compose -f docker-compose.prod.yml up -d --build

    - name: Verify deployment
      run: |
        sleep 10
        curl -f http://localhost:8000/ || exit 1

