name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'
        cache-dependency-path: server/yarn.lock
    
    - name: Install dependencies
      run: yarn install
      working-directory: ./server
    
    - name: Run type checking
      run: yarn build
      working-directory: ./server

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Login DockerHub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD 
      
    - name: Build the Docker image
      run: docker build -t prasadnarkhedkar/wordgame:latest .
      working-directory: ./server

    - name: Push to DockerHub
      run: docker push prasadnarkhedkar/wordgame:latest
      
